services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: github-automation
    ports:
      - "8080:8080"
    # volumes:
    #   - .:/app
    # environment:
    #   - NODE_ENV=development
