name: Github Actions Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code for github actions deployment
        uses: actions/checkout@v5

      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: "24.18.1"

      # - run: node -v
      # - run: npm -v

      - name: Deploy via Github Runner
        # uses: appleboy/ssh-action@v1.0.3

        # with:
        #   host: ${{ secrets.SSH_HOST }}
        #   username: ${{ secrets.SSH_USERNAME }}
        #   key: ${{ secrets.SSH_KEY }}
        run: |
          cd /var/www/html/Express-application-github-automation
          git pull
          docker compose up -d --build
